"""fireup database

Revision ID: 0dbb66f71f0b
Revises: 
Create Date: 2024-05-20 21:19:24.881008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbb66f71f0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('cpfP', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mail', sa.String(length=128), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cpfP')
    )
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professor_mail'), ['mail'], unique=True)

    op.create_table('school',
    sa.Column('inep', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('city', sa.String(length=27), nullable=False),
    sa.Column('zone', sa.String(length=6), nullable=False),
    sa.Column('tier', sa.String(length=7), nullable=False),
    sa.Column('code', sa.String(length=9), nullable=False),
    sa.Column('pnum', sa.String(length=14), nullable=True),
    sa.Column('latd', sa.Float(), nullable=True),
    sa.Column('lotd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('inep')
    )
    op.create_table('student',
    sa.Column('cpfS', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bday', sa.String(length=8), nullable=False),
    sa.Column('mail', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('cpfS')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_mail'), ['mail'], unique=True)

    op.create_table('enrollment',
    sa.Column('cpfS', sa.String(length=11), nullable=False),
    sa.Column('cpfP', sa.String(length=11), nullable=False),
    sa.Column('inep', sa.String(length=11), nullable=False),
    sa.Column('year', sa.String(length=11), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('gift', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['cpfP'], ['professor.cpfP'], ),
    sa.ForeignKeyConstraint(['cpfS'], ['student.cpfS'], ),
    sa.ForeignKeyConstraint(['inep'], ['school.inep'], ),
    sa.PrimaryKeyConstraint('cpfS', 'cpfP', 'inep', 'year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_mail'))

    op.drop_table('student')
    op.drop_table('school')
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professor_mail'))

    op.drop_table('professor')
    # ### end Alembic commands ###
