"""starting a new database

Revision ID: 614cb64634ec
Revises: 
Create Date: 2024-05-22 14:30:49.707997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614cb64634ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index('ix_professor_mail')
        batch_op.create_index(batch_op.f('ix_professor_email'), ['email'], unique=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('birth',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('ix_student_mail')
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_email'))
        batch_op.create_index('ix_student_mail', ['email'], unique=1)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('birth',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.alter_column('fname',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professor_email'))
        batch_op.create_index('ix_professor_mail', ['email'], unique=1)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
