"""create tables

Revision ID: d5406d1a9811
Revises: 
Create Date: 2024-05-26 15:42:30.285673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5406d1a9811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('taxnr', sa.String(length=11), nullable=False),
    sa.Column('fname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pswrd', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('taxnr')
    )
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professor_email'), ['email'], unique=True)

    op.create_table('school',
    sa.Column('inep', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('city', sa.String(length=27), nullable=False),
    sa.Column('zone', sa.String(length=6), nullable=False),
    sa.Column('tier', sa.String(length=7), nullable=False),
    sa.Column('code', sa.String(length=9), nullable=False),
    sa.Column('pnum', sa.String(length=14), nullable=True),
    sa.Column('latd', sa.Float(), nullable=True),
    sa.Column('lotd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('inep')
    )
    op.create_table('student',
    sa.Column('cpfnr', sa.String(length=11), nullable=False),
    sa.Column('fname', sa.String(length=255), nullable=False),
    sa.Column('birth', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cpfnr')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)

    op.create_table('enrollment',
    sa.Column('cpfnr', sa.String(length=11), nullable=False),
    sa.Column('taxnr', sa.String(length=11), nullable=False),
    sa.Column('inep', sa.String(length=8), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('need', sa.String(length=255), nullable=True),
    sa.Column('gift', sa.CHAR(), nullable=False),
    sa.ForeignKeyConstraint(['cpfnr'], ['student.cpfnr'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['inep'], ['school.inep'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['taxnr'], ['professor.taxnr'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('cpfnr', 'taxnr', 'inep', 'year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    op.drop_table('school')
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professor_email'))

    op.drop_table('professor')
    # ### end Alembic commands ###
